{{- range .Values.stages }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-stage-{{ .name }}
  namespace: dynamic-stages
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dynamic-stage-{{ .name }}
  template:
    metadata:
      labels:
        app: dynamic-stage-{{ .name }}
    spec:
      containers:
      - name: dynamic-stage-{{ .name }}
        image: {{ printf "var-echo:%s" .revision }}
        ports:
        - containerPort: 8080
        env:
        - name: LE_ENV_VAR
          value: env-var-on-dynamic-stage-{{ .name }}
---
{{- end }}