{{- range .stages }}
apiVersion: v1
kind: Service
metadata:
  name: dynamic-stage-{{ .name }}
  namespace: dynamic-stages
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: dynamic-stage-{{ .name }}
---
{{- end }}